# .bashrc

# User specific aliases and functions

alias rm='rm -i'
alias cp='cp -i'
alias mv='mv -i'

# Source global definitions
if [ -f /etc/bashrc ]; then
	. /etc/bashrc
fi

alias python=python3

echo 'going to add elastic service using the following command: rucio-admin config set --section hermes --option services_list --value elastic' 

